Feature/task 138 test refresh values structure
virtualsatellite/VirtualSatellite4-CEF pull request #139
Opened 2020-10-09 14:51 UTC by Anna-Lena-DLR

Added UI test for CEF TreeTable to check that tree values and tree structure are updated when model values change.

2020-10-12 19:59 UTC, SaMuellerDLR requested changes
Only a minor refactoring and its good to go.

2020-10-12 19:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.cef.swtbot.test/src/de/dlr/sc/virsat/cef/swtbot/test/CefRefreshValueAndStructureTest.java
> +		systemParametersTree.getAllItems()[MODE_DURATION_ROW_INDEX].expand();
`systemParametersTree.getAllItems()[MODE_DURATION_ROW_INDEX]` this expression seems to appear a couple of times. Maybe we can put the item into a variable?

2020-10-14 16:14 UTC, andriikovalov-dlr approved these changes

2020-10-15 15:20 UTC, SaMuellerDLR approved these changes
Approved!

2020-10-15 16:23 UTC, merged